# Generated by Django 2.0.12 on 2020-04-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_total',
            field=models.FloatField(default=0),
        ),
    ]
