# Generated by Django 2.0.12 on 2020-04-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart_total',
        ),
    ]
