# Generated by Django 2.0.12 on 2020-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_total',
            field=models.FloatField(default=0),
        ),
    ]
