# Generated by Django 4.2.28 on 2026-02-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('num_of_topings', models.IntegerField(blank=True, null=True)),
                ('topping1', models.CharField(blank=True, max_length=64, null=True)),
                ('topping2', models.CharField(blank=True, max_length=64, null=True)),
                ('topping3', models.CharField(blank=True, max_length=64, null=True)),
                ('topping4', models.CharField(blank=True, max_length=64, null=True)),
                ('sub_extras_count', models.IntegerField(blank=True, null=True)),
                ('extra_1', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_2', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_3', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_4', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(max_length=64)),
                ('price_large', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(blank=True, max_length=64, null=True)),
                ('mon', models.CharField(blank=True, max_length=64, null=True)),
                ('tue', models.CharField(blank=True, max_length=64, null=True)),
                ('wed', models.CharField(blank=True, max_length=64, null=True)),
                ('thu', models.CharField(blank=True, max_length=64, null=True)),
                ('fri', models.CharField(blank=True, max_length=64, null=True)),
                ('sat', models.CharField(blank=True, max_length=64, null=True)),
                ('msg', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(blank=True, max_length=64)),
                ('price_large', models.CharField(max_length=64)),
                ('extra_cheese', models.BooleanField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(max_length=64)),
                ('price_large', models.CharField(max_length=64)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.topping')),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(max_length=64)),
                ('price_large', models.CharField(max_length=64)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.FloatField(blank=True, null=True)),
                ('item', models.ManyToManyField(blank=True, to='orders.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(blank=True, to='orders.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
