# Generated by Django 2.0.12 on 2020-01-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200103_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(max_length=64)),
                ('price_large', models.CharField(max_length=64)),
                ('extra_cheese', models.BooleanField(max_length=64)),
            ],
        ),
    ]
