# Generated by Django 2.0.12 on 2020-01-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(blank=True, max_length=64)),
                ('price_large', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.CharField(blank=True, max_length=64)),
                ('price_large', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
