# Generated by Django 2.0.12 on 2020-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200115_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='price_small',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price_small',
            field=models.CharField(max_length=64),
        ),
    ]
