# Generated by Django 2.0.12 on 2020-01-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
