# Generated by Django 2.0.12 on 2020-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200422_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='extra_cheese',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra_green_pepper',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra_mushroom',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra_onion',
            field=models.NullBooleanField(),
        ),
    ]
