# Generated by Django 2.0.12 on 2020-04-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200425_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='extra_cheese',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra_green_pepper',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra_mushroom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra_onion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
