# Generated by Django 2.0.12 on 2020-04-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200426_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_total',
            field=models.FloatField(default=0),
        ),
    ]
