# Generated by Django 2.0.12 on 2020-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_cartitem_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_total',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.FloatField(default=0),
        ),
    ]
