# Generated by Django 2.0.12 on 2020-04-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200426_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.FloatField(blank=True),
        ),
    ]
