# Generated by Django 2.0.12 on 2020-04-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
