# Generated by Django 2.0.12 on 2020-04-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(blank=True, max_length=64, null=True)),
                ('mon', models.CharField(blank=True, max_length=64, null=True)),
                ('tue', models.CharField(blank=True, max_length=64, null=True)),
                ('wed', models.CharField(blank=True, max_length=64, null=True)),
                ('thu', models.CharField(blank=True, max_length=64, null=True)),
                ('fri', models.CharField(blank=True, max_length=64, null=True)),
                ('sat', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
